apiVersion: v1
kind: Service
metadata:
  name: kubesrv-svc
  namespace: kubesrv-ns
  labels:
    app: kubesrv
spec:
  type: ClusterIP
  selector:
    app: kubesrv
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
