#!/bin/sh
# embed-static.sh - Converts static files to C header for embedding
# Usage: ./scripts/embed-static.sh

set -e

STATIC_DIR="static"
OUTPUT_DIR="src/generated"
OUTPUT_FILE="$OUTPUT_DIR/static_files.h"

mkdir -p "$OUTPUT_DIR"

# Minify CSS by removing comments, extra whitespace
minify_css() {
    # Remove comments, collapse whitespace, remove newlines
    sed 's|/\*[^*]*\*+([^/*][^*]*\*+)*/||g' | \
    tr '\n' ' ' | \
    sed 's/  */ /g' | \
    sed 's/ *{ */{/g' | \
    sed 's/ *} */}/g' | \
    sed 's/ *: */:/g' | \
    sed 's/ *; */;/g' | \
    sed 's/ *, */,/g'
}

# Minify HTML by collapsing whitespace
minify_html() {
    tr '\n' ' ' | sed 's/  */ /g' | sed 's/> </></g'
}

# Read and minify CSS
CSS_CONTENT=$(cat "$STATIC_DIR/style.css" | minify_css)

# Read HTML and inline the CSS
HTML_CONTENT=$(cat "$STATIC_DIR/index.html" | \
    sed '/<link rel="stylesheet".*>/d' | \
    sed "s|</head>|<style>$CSS_CONTENT</style></head>|")

# Minify final HTML
HTML_MINIFIED=$(echo "$HTML_CONTENT" | minify_html)

# Escape for C string
escape_c_string() {
    sed 's/\\/\\\\/g' | \
    sed 's/"/\\"/g' | \
    sed 's/%/%%/g'
}

HTML_ESCAPED=$(echo "$HTML_MINIFIED" | escape_c_string)

# Generate header file
cat > "$OUTPUT_FILE" << 'HEADER_START'
/*
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/embed-static.sh
 */

#ifndef STATIC_FILES_H
#define STATIC_FILES_H

HEADER_START

echo "static const char *INDEX_HTML = \"$HTML_ESCAPED\";" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'HEADER_END'

#endif /* STATIC_FILES_H */
HEADER_END

echo "Generated: $OUTPUT_FILE"
