#ifndef KUBESRV_CONFIG_H
#define KUBESRV_CONFIG_H

#define KUBESRV_VERSION     "1.2.0"
#define KUBESRV_DEFAULT_PORT 80
#define KUBESRV_BUFFER_SIZE  8192
#define KUBESRV_BACKLOG      64
#define KUBESRV_HOSTNAME_MAX 256
#define KUBESRV_PATH_MAX     256
#define KUBESRV_READY_DELAY  10
#define KUBESRV_MAX_HEADER   2048
#define KUBESRV_MAX_HEADERS  32

#endif
