apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubesrv.fullname" . }}-config
  labels:
    {{- include "kubesrv.labels" . | nindent 4 }}
data:
  message.txt: {{ .Values.config.message | quote }}
